sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPBUNpiqnX1aE3oMxrz
    access-key-secret: RjBtzgZGxggKthpFmauys1qU3u1Fts
    bucket-name: congmu-sky-takeaway

  redis:
    host: localhost
    port: 6379
    password:
    database: 10

  wechat:
    appid: wx8743e5022b15b395
    secret: 89eb2de5a2405df1f50848232c194556
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php